AST: Add scaffolding and definitions for the AST definition macro
hash-org/lang pull request #520
Opened 2022-09-21 23:26 UTC by kontheocharis

The macro is named `define_tree!` and it essentially takes all the items of the AST definition and (will eventually) produce visitor and walker definitions for them. This is an intermediate PR to keep the code size small; the parsing has been implemented but the emitting has not.

Working towards #519.

2022-09-21 23:45 UTC, feds01 requested changes
mui bien sie

2022-09-21 23:45 UTC, feds01 commented on compiler/hash-tree-def/src/parsing.rs
> +        println!("{:#?}", value);
remove?

2022-09-21 23:45 UTC, feds01 commented on compiler/hash-tree-def/src/parsing.rs
> +        }
would be nice to use `if_chain!` here but not necessarily required.

2022-09-22 13:05 UTC, feds01 approved these changes

2022-09-22 16:05 UTC, merged

2022-09-22 16:06 UTC, kontheocharis commented on compiler/hash-tree-def/src/parsing.rs
> +        println!("{:#?}", value);
Will tackle in final PR